### ISSUE TITLE
For posterity: A script to migrate *away* from `sauth` to regular sqlite3 auth

### ISSUE THREAD

**Issue by sofar** [shivajiva101/sauth#16]
I used this script to migrate my server from sauth to auth. There's not enough reason for me right now to maintain a server with a very uncommon auth backend. More people may be interested in this, so I'm leaving it here as-is. Could be maybe merged, or posted on the wiki, or something. Don't really care :).

```
#!/bin/env python3

# copy all auth entries from an sauth.sqlite file into an existing
# (but empty) auth.sqlite from minetest's normal sqlite3 auth backend

# You'll need an auth.sqlite file from just any minetest world. This
# script will delete all the entries from it. Or you can manually create
# an empty auth.sqlite.

# sauth has a small bug where there may be duplicate `name` entries in the
# auth table, and this script works around them with a `try: except:`
# block. Otherwise it's a very straight copy over of auth and privileges.

# make sure to edit `world.mt` after this runs to assure `auth_backend = sqlite3`
# and `load_mod_sauth = false`

import sqlite3
import sys

try:
    from_name = sys.argv[1]
    to_name = sys.argv[2]
except:
    print("Usage: $0 from_db.sqlite3 to_db.sqlite3")
    exit();

try:
    from_db = sqlite3.connect(from_name)
except:
    print("$1 must be the path to sauth.sqlite3")
    exit();

try:
    to_db = sqlite3.connect(to_name)
except:
    print("$2 must be the path to auth.sqlite3")
    exit();


print("This program will import all auth entries from " + from_name)
print("and import them into " + to_name + ".")
print("to do this, it has to delete all the entries in " + to_name)
print("if you don't want this, press ^C now")

input("Press Enter to continue...")

from_cur = from_db.cursor()
to_cur = to_db.cursor()

print("Deleting all content from " + to_name)
to_cur.execute("delete from auth;")
to_db.commit()
to_cur.execute("delete from user_privileges;")
to_db.commit()

count = 0
last_id = 0

print("Copying entries...")
for row in from_cur.execute("SELECT id, name, password, privileges, last_login FROM auth;"):
    count += 1
    if count % 100 == 0:
        print(count)

    last_id = row[0]

    try:
        to_cur.execute("INSERT INTO auth (id, name, password, last_login) VALUES ("
                       + str(row[0]) + ", \"" + row[1] + "\", \"" + row[2] + "\", "
                       + str(row[4]) + ");")
        to_db.commit()
    except:
        print("An error occured for id " + str(row[0]) + " - skipping")
        continue

    try:
        for priv in row[3].replace(" ", "").split(","):
            to_cur.execute("INSERT INTO user_privileges (id, privilege) VALUES ("
                           + str(row[0]) + ", \"" + priv + "\");")
            to_db.commit()
    except:
        print("An error occured for id " + str(row[0]) + " - skipping")
        continue

print(str(count) + " records written, last id = " + str(last_id)) 

# end
from_db.close()
to_db.commit()
to_db.close()
```

**Comment by shivajiva101** [comment]
Well that's about as lazy as it gets for a non issue 'issue', happy to accept a pr that adds the script to the tools folder and updates the readme if you want to do this properly...

**Comment by sofar** [comment]
We can asbolutely do this. I wanted to make sure you didn't have any comments on it. E.g. we can just have the script create a new, empty `auth.sqlite`, we can have the script renumer the `id`s used. We can have the script scan for duplicate names etc. etc.

If you want me to start a PR, I will do so.

**Comment by shivajiva101** [comment]
Yes please.

I think it's good for users to have an option to climb back out of situations where data should be retained rather than trapped in the consequences of an earlier decision. Preferably with the least amount of effort.

If ```auth.sqlite``` exists then it holds redundant data from the moment sauth's import script is run. Logically if the existing ```auth.sqlite``` is backed up by the script prior to opening and clearing the contents all bases are covered from a data loss perspective, as for id remapping that would only apply to a merge of different data sets which shouldn't be a scenario, but for obvious reasons the duplicates need to be caught and handled, with last login taking precedence for those cases I guess.

**Comment by sofar** [comment]
We could even write the conversion script to go both ways. That would make adopting really painless for any new user - shouldn't be overly difficult.

**Comment by shivajiva101** [comment]
I have no objections to it working both ways, it will provide a common interface so that's a plus for the user

**Comment by sofar** [comment]
#17

**Comment by shivajiva101** [comment]
I've been giving this some thought and the optimum solution going forward is to modify sauth to use the auth.sqlite db so there would be nothing to do except enable or disable the sauth mod itself. Obviously at the point of conception that wasn't a possibility but it certainly is now.

**Comment by shivajiva101** [comment]
If you want something that works quicker you can use https://github.com/shivajiva101/sauth/blob/dev-0.5/tools/auth-convert.py
