### ISSUE TITLE
auth.sql doesn't update _s import correctly

### ISSUE THREAD

**Issue by ghost** [shivajiva101/sauth#2]
When trying to populate the sauth.sqlite with .read auth.sql, I noted a syntax error message from sqlite3 cli.
I found that column "import" in table "_s" would not update from false to true as a result of the error.

I'm sure there's a prettier way, but changing:
`		stmt = "UPDATE _s (import) VALUES ('true');\n"`
to

`		stmt = "UPDATE _s SET import='true';\n"`
Resolved this for me.

**Comment by shivajiva101** [comment]
code updated

**Comment by shivajiva101** [comment]
looks like I forgot to delete sauth.sqlite after the export, hence the poorly formed UPDATE which was meant to be an INSERT judging from the format I was trying to fold together. The changes have been pushed upstream on the basis of my test, I would appreciate you testing to verify that it works for you

**Comment by ghost** [comment]
Just happened to notice the latest change. I like it. But won't be able to test until tomorrow.
