### ISSUE TITLE
get_auth in sauth.auth_handler "attempt to index a nil value"

### ISSUE THREAD

**Issue by ghost** [shivajiva101/sauth#3]
core.auth_table[name].privileges
Doesn't seem to exist?

Had to resort to older version to run :(

**Comment by shivajiva101** [comment]
Could you provide a little more information about the point the error was triggered pls?
I think you are on to something, line 160 has lost it's context with the addition of the cache, still interested in the context from the debug log though if possible. Feel free to try the test branch with the proposed change.

**Comment by ghost** [comment]
No access to the files at the moment. But the crash would occur on login of first player after populating .sqlite from .sql and setting  the import record to true.
I did a print(dump(core.auth_table)) before line 160 to see exactly what was nil and saw the entire core.auth table was empty.
Would be happy to test your test branch tomorrow :)

**Comment by ghost** [comment]
I've been testing your test branch (comit 1fb6ac0dc484873174023a3f641b313e7bd15aab) and I really like it. After using sqlite3 cli to populate the database, I'm able to log in with various users with no issue and privs are preserved.
My only concern would be that it's important for the server operator to know if the server is restarted before the .sql file is imported. A auth.sqlite db is created. If the .sql is then imported, there is a risk of duplicate player entries if anyone were to join before the import. Also privileged users will have default privs given to them as the real privs will be stored in the .sql file.
 There will also be two "true" entries in the import column rather than just the one. Not sure if that would be harmful or not.

**Comment by shivajiva101** [comment]
I use limit for the retrieval so it shouldn't be an issue but I've updated the readme to express the risk of duplication if sauth.sqlite exists when doing the import, thanks for testing :)
