### ISSUE TITLE
Changing password of offline player results in crash.

### ISSUE THREAD

**Issue by ghost** [shivajiva101/sauth#4]
It seems sauth.auth_handler.set_password will attempt to add password to empty cache table of offline player resulting in a crash.  I only tested on online players yesterday.

A quick and likely dirty fix confirms and seems to resolve this:

```
	set_password = function(name, password)
		assert(type(name) == 'string')
		assert(type(password) == 'string')
		-- get player record
		if get_record(name) == nil then
			sauth.auth_handler.create_auth(name, password)
		else
			-- if player offline, don't touch cash or crash
			if auth_table[name] == nil then
				update_password(name, password)
			else			
				update_password(name, password)
				auth_table[name].password = password
			end
		end
		return true
	end,
```

**Comment by shivajiva101** [comment]
Thanks for testing thoroughly, added checks for password & privilege change for offline players to main branch  :)
