### ISSUE TITLE
One reason database was getting hit hard with massive requests on our server.

### ISSUE THREAD

**Issue by ghost** [shivajiva101/sauth#6]
You may remember I was having issues with massive lag on our server that was resolved by removing sauth and reverting to the original auth_handler.
I could not duplicate on a dev server that was a exact clone of our server without first trying out sauth again multiple times on the production server with added "debug" lines in the sauth code.
I found that the call to the  function "get_record(name)" within the "get_auth" was repeatedly trying to get a record without a player name.
I found that protector_redo checks the privs of a "digger"  with any digging. This also applies to mobs. Like sheep eating grass. The sheeps privs are checked, and they don't have a player name :D
This can also be confirmed when using TNT. One TNT will cause 9 get_records to occur without a player name.  9 TNT's made 2098 queries. At nearly the same time!

My work around was to reject requests for records without a player name. With a few days in production it seems to work without any known (so far) bad side affects. I think I'd rather prevent the protection mod from making the priv checks to begin with, but my attempt broke TNT from doing damage to surrounding nodes (ooops)

This is what I did to reject the requests, and give a message about the no name record request:
```
		-- Return password,privileges,last_login
		assert(type(name) == 'string')

		if name == nil or name == '' or name == ' ' then
			minetest.log("sauth_handler: Name was missing in call to get_auth. Rejected.")
			return nil
		end

		add_to_cache = add_to_cache or true -- Assert caching on missing param
		local r = auth_table[name]
		-- Check and load db record if reqd
		if r == nil then
			minetest.log("get_record from get_auth: "..name)
			r = get_record(name)
	  	else
		  	return auth_table[name]	-- cached copy			
	  	end
		-- Return nil on missing entry
```
Hope this is useful to someone.

**Comment by shivajiva101** [comment]
Thanks for the info, I'll get it added to the code :+1:

**Comment by shivajiva101** [comment]
added in commit https://github.com/shivajiva101/sauth/commit/2a35105a76c2f4918087709662bfaef8a9ece873 :smiley:
