### ISSUE TITLE
Mods using auth_table (default auth handler) may lag server with sauth handler.

### ISSUE THREAD

**Issue by ghost** [shivajiva101/sauth#7]
This isn't a issue you will likely be able to avoid with this mod, but I thought you would like to know.
One of our reasons for sauth being unusable on our server was that we used the Name Restrictions mod.

The name restriction mod goes through the entire auth_table supplied by the auth.txt with several intensive searches. As sauth's auth_table is cached, many hundreds of records are queried and compared for lots of things. As this happens on minetest.register_on_prejoinplayer, the cause of the lag isn't easily discovered.
As I depend on the name_restrictions mod. I made use of sauth's sqlite3 connection and made a custom query to load all names into a table on startup. Then I modified the name_restrictions mod to use that name cache rather than hit the auth_table.

Now that we are actually able to use sauth, and have the luxury of working with a database rather than a text file, we are thrilled with all the hard work you've done on sauth. 
Thanks!

**Comment by shivajiva101** [comment]
you make a good case for adding name restriction functionality to sauth :wink:

**Comment by shivajiva101** [comment]
this functionality may interest you https://github.com/shivajiva101/sauth/blob/master/init.lua#L285
it could easily be extended to the whole list of names

**Comment by ghost** [comment]
So if I'm understanding you correctly...  I can create a table of just the names of every player in the database with something like this?

`huge_namelist = sauth.auth_handler.name_search("%")`

Using a sqlite3 wildcard rather than a nil name? And this would be global? If so that would make maintenance a whole lot less complicated :)
Then I can filter all day long at the price of one database call at startup. Provided the table is updated with new registrations of course.
We've got enough memory (I hope) that keeping just the names cached for repeated searches seems like more of a performance gain than hitting the database any more than I need to.

**Comment by shivajiva101** [comment]
Yes that was the idea :grin: 
Like this https://github.com/shivajiva101/name_restrictions/blob/sqlite/init.lua
